services:
  softwarehouse:
    build: .
    container_name: softwarehouse
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - softwarehouse_db
    networks:
      - softwarehouse_network

  softwarehouse_db:
    image: mysql:5.7
    container_name: softwarehouse_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DEVELOPMENT}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - softwarehouse_network

  softwarehouse_delete_seeds:
    build: .
    container_name: softwarehouse_delete_seeds
    command: sh -c "npx sequelize-cli db:seed:undo:all"
    depends_on:
      - softwarehouse_db
    env_file:
      - .env
    networks:
      - softwarehouse_network

  softwarehouse_delete_migrations:
    build: .
    container_name: softwarehouse_delete_migrations
    command: sh -c "npx sequelize-cli db:migrate:undo:all"
    depends_on:
      - softwarehouse_db
    env_file:
      - .env
    networks:
      - softwarehouse_network

networks:
  softwarehouse_network:

volumes:
  db_data: